language: node_js
node_js:
  - "9.5.0"

script:
  - cd site
  - rm -rf public/*
  - ../binaries/hugo
  - cd ../

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master