language: node_js
node_js:
  - "9.4.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - cd site
  - rm -rf public/*
  - ../binaries/hugo
  - firebase deploy --token=${FIREBASE_API_TOKEN}